### ISSUE TITLE
Cannot find module 'angular2-meteor/mongo_cursor_differ' from app/pages/page1/page1.ts

### ISSUE THREAD

**Issue by mjwheatley** [nelsonec87/ionic2-meteor-seed#4]
Is this import needed?  I comment out this import and the corresponding use in the providers and it still seems to work.

**Comment by nelsonec87** [comment]
Since 15 hours ago (version 0.5.3 of angular2-meteor release) it is not necessary anymore! In 0.5.3 it was necessary to allow you to iterate Mongo cursors in the view  (with *ngFor).

I'll test the new version and update the repo, thx
